workflows:
  android-build:
    name: FlorisBoard Build

    max_build_duration: 60

    environment:
      java: 17

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Show Java version
        script: java -version

      - name: Give Gradle permission
        script: chmod +x ./gradlew

      - name: Clean project
        script: ./gradlew clean

      - name: Build Debug APK
        script: ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk
