workflows:
  android-build:
    name: FlorisBoard APK Build

    max_build_duration: 60

    environment:
      java: 17

      android_signing:
        - keystore_reference

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Set execute permission
        script: chmod +x gradlew

      - name: Clean Gradle
        script: ./gradlew clean

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug \
          --no-daemon \
          --stacktrace \
          --warning-mode all

    artifacts:
      - app/build/outputs/**/*.apk
